CREATE DATABASE SG_MKP
ON PRIMARY (
NAME = 'SG_MKP',
FILENAME = 'D:\SG_MKP_Project\SG_MKP_BD_Dados\SG_MKP.mdf',
SIZE = 10240 KB,
MAXSIZE = UNLIMITED,
FILEGROWTH = 1024 KB
)
LOG ON (
NAME = 'SG_MKP_log',
FILENAME = 'D:\SG_MKP_Project\SG_MKP_BD_Dados\SG_MKP_log.ldf',
SIZE = 5120 KB,
MAXSIZE = UNLIMITED,
FILEGROWTH = 10 %
);

USE SG_MKP;

CREATE TABLE dbo.PRODUTO (
  PRO_CODIGO int IDENTITY,
  PRO_DESCRICAO varchar(150) NOT NULL,
  PRO_CATEGORIA varchar(50) NOT NULL,
  PRO_VALORVENDA decimal(18, 2) NOT NULL DEFAULT (0),
  --PRO_IMAGEM image NULL,
  PRO_IMAGEM_1 image NULL,
  PRO_IMAGEM_2 image NULL,
  PRO_IMAGEM_3 image NULL,
  --PRO_IMAGEM_4 image NULL,
  --PRO_IMAGEM_5 image NULL,
  PRO_CONDICAOPRODUTO varchar(50) NOT NULL,
  PRO_QUANTIDADEDISPONIVEL float NOT NULL,
  CONSTRAINT PK_PRODUTO_PRO_CODIGO PRIMARY KEY CLUSTERED (PRO_CODIGO)
);

CREATE TABLE dbo.USUARIO (
  USU_ID int IDENTITY,
  USU_USUARIO varchar(50) NOT NULL,
  USU_SENHA varchar(20) NOT NULL,
  CONSTRAINT PK_USUARIO_USU_ID PRIMARY KEY CLUSTERED (USU_ID)
);

EXEC sys.sp_addextendedproperty 'MS_Description', 'Tabela de Produtos', 'SCHEMA', 'dbo', 'TABLE', 'PRODUTO';

EXEC sys.sp_addextendedproperty 'MS_Description', 'Tabela de Usuarios', 'SCHEMA', 'dbo', 'TABLE', 'USUARIO';

INSERT INTO dbo.USUARIO (USU_USUARIO, USU_SENHA) VALUES
('guzzoandre.ag@outlook.com', 'Ag*99345038'),
('guzzo', '1234');

INSERT INTO dbo.PRODUTO (PRO_DESCRICAO, PRO_CATEGORIA, PRO_VALORVENDA, PRO_IMAGEM, PRO_IMAGEM_1,
PRO_IMAGEM_2, PRO_IMAGEM_3, PRO_IMAGEM_4, PRO_IMAGEM_5, PRO_CONDICAOPRODUTO, PRO_QUANTIDADEDISPONIVEL)
  VALUES ('BATATA FRITA 1KG', 'ALIMENTOS', 13.49, NULL, NULL, NULL, NULL, NULL, NULL, 'NOVO', 50),
  ('LEITE 1L', 'LATICINIOS', 3.89, NULL, NULL, NULL, NULL, NULL, NULL, 'NOVO', 139)